server {
    listen 80;
    listen [::]:80;
    server_name cam.fermi.uz;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name cam.fermi.uz;

    ssl_certificate /etc/ssl/camera-devflix/fullchain.pem;
    ssl_certificate_key /etc/ssl/camera-devflix/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/cam.fermi.uz;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
