import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.database import Base


class Report(Base):
    """Matches src/types/index.ts `Report`. `source='rule'` reports are
    generated by app/services/report_generator.py from real data already
    in this database (attendance %, event counts, camera uptime) — no
    fabricated numbers. `source='llm'` is schema-ready but has no
    generator wired in yet: that needs a real LLM API key, which isn't
    configured here (see the router docstring)."""

    __tablename__ = "reports"
    __table_args__ = (
        CheckConstraint("period IN ('Kunlik', 'Haftalik', 'Oylik')", name="ck_reports_period"),
        CheckConstraint("source IN ('rule', 'llm')", name="ck_reports_source"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())
    period: Mapped[str] = mapped_column(String, nullable=False)
    period_label: Mapped[str] = mapped_column(String, nullable=False)
    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), index=True)
    source: Mapped[str] = mapped_column(String, nullable=False, default="rule")
    summary: Mapped[str] = mapped_column(String, nullable=False)
    body: Mapped[str] = mapped_column(String, nullable=False)
    stats: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    # Sarlavhali jadvallar (modul bo'yicha taqsimot, eng ko'p signal
    # bergan kameralar va h.k.). Nullable — bu ustun qo'shilishidan
    # oldin yaratilgan hisobotlarda u yo'q, va eski hisobotni qayta
    # yozish uni SOXTALASHTIRISH bo'lardi: o'sha paytdagi ma'lumot
    # allaqachon o'zgargan.
    sections: Mapped[list | None] = mapped_column(JSONB, nullable=True)
