"""add camera last_seen_at for reachability tracking

Revision ID: 08b46618eee1
Revises: c0c6a9257960
Create Date: 2026-08-04 14:13:54.538156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b46618eee1'
down_revision: Union[str, None] = 'c0c6a9257960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'last_seen_at')
    # ### end Alembic commands ###
