"""add biometric photo key and embedding to students_staff

Revision ID: 31169d7f9377
Revises: e92a183b1366
Create Date: 2026-08-03 11:59:32.171488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31169d7f9377'
down_revision: Union[str, None] = 'e92a183b1366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_staff', sa.Column('biometric_photo_key', sa.String(), nullable=True))
    op.add_column('students_staff', sa.Column('biometric_embedding', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students_staff', 'biometric_embedding')
    op.drop_column('students_staff', 'biometric_photo_key')
    # ### end Alembic commands ###
