"""add teacher punctuality fields to lesson_sessions

Revision ID: 8a3bf936ba5b
Revises: 08b46618eee1
Create Date: 2026-08-13 13:40:57.828642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3bf936ba5b'
down_revision: Union[str, None] = '08b46618eee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_sessions', sa.Column('teacher_id', sa.UUID(), nullable=True))
    op.add_column('lesson_sessions', sa.Column('camera_id', sa.UUID(), nullable=True))
    op.add_column('lesson_sessions', sa.Column('scheduled_start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lesson_sessions', sa.Column('punctuality_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_lesson_sessions_camera_id'), 'lesson_sessions', ['camera_id'], unique=False)
    op.create_index(op.f('ix_lesson_sessions_teacher_id'), 'lesson_sessions', ['teacher_id'], unique=False)
    op.create_foreign_key(None, 'lesson_sessions', 'students_staff', ['teacher_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'lesson_sessions', 'cameras', ['camera_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lesson_sessions', type_='foreignkey')
    op.drop_constraint(None, 'lesson_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_lesson_sessions_teacher_id'), table_name='lesson_sessions')
    op.drop_index(op.f('ix_lesson_sessions_camera_id'), table_name='lesson_sessions')
    op.drop_column('lesson_sessions', 'punctuality_checked_at')
    op.drop_column('lesson_sessions', 'scheduled_start_time')
    op.drop_column('lesson_sessions', 'camera_id')
    op.drop_column('lesson_sessions', 'teacher_id')
    # ### end Alembic commands ###
