"""add restricted_zone_polygon to cameras

Revision ID: a3acff7e6c11
Revises: 8a3bf936ba5b
Create Date: 2026-08-13 15:13:06.564976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3acff7e6c11'
down_revision: Union[str, None] = '8a3bf936ba5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('restricted_zone_polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'restricted_zone_polygon')
    # ### end Alembic commands ###
