"""add attendance, lesson_sessions, reports tables

Revision ID: bb3044f649d2
Revises: eca36e097307
Create Date: 2026-08-01 15:00:17.354538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb3044f649d2'
down_revision: Union[str, None] = 'eca36e097307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('faculty', sa.String(), nullable=False),
    sa.Column('teacher', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('attention_score', sa.Integer(), nullable=False),
    sa.Column('sleep_incidents', sa.Integer(), nullable=False),
    sa.Column('teacher_activity_score', sa.Integer(), nullable=False),
    sa.Column('teacher_on_time', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_sessions_date'), 'lesson_sessions', ['date'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('period_label', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("period IN ('Kunlik', 'Haftalik', 'Oylik')", name='ck_reports_period'),
    sa.CheckConstraint("source IN ('rule', 'llm')", name='ck_reports_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_generated_at'), 'reports', ['generated_at'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_staff_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.CheckConstraint("status IN ('keldi', 'kelmadi', 'kech_keldi', 'dam_olish')", name='ck_attendance_status'),
    sa.ForeignKeyConstraint(['student_staff_id'], ['students_staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_staff_id', 'date', name='uq_attendance_person_date')
    )
    op.create_index(op.f('ix_attendance_records_student_staff_id'), 'attendance_records', ['student_staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_student_staff_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_reports_generated_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_lesson_sessions_date'), table_name='lesson_sessions')
    op.drop_table('lesson_sessions')
    # ### end Alembic commands ###
