"""add unique constraint to faculty and building names

Revision ID: c0c6a9257960
Revises: 31169d7f9377
Create Date: 2026-08-03 12:24:02.185780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c6a9257960'
down_revision: Union[str, None] = '31169d7f9377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'buildings', ['name'])
    op.create_unique_constraint(None, 'faculties', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faculties', type_='unique')
    op.drop_constraint(None, 'buildings', type_='unique')
    # ### end Alembic commands ###
