"""add events table

Revision ID: d1a4b623f5a6
Revises: f4c9709f9288
Create Date: 2026-08-01 13:43:29.676176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a4b623f5a6'
down_revision: Union[str, None] = 'f4c9709f9288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('camera_name', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('module_code', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('person_name', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.CheckConstraint("severity IN ('past', 'o''rta', 'yuqori')", name='ck_events_severity'),
    sa.CheckConstraint("status IN ('yangi', 'tasdiqlangan', 'rad_etilgan')", name='ck_events_status'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
