"""add ai_modules table

Revision ID: eca36e097307
Revises: d1a4b623f5a6
Create Date: 2026-08-01 14:07:57.779900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca36e097307'
down_revision: Union[str, None] = 'd1a4b623f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_modules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('sensitivity', sa.String(), nullable=False),
    sa.Column('camera_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("sensitivity IN ('past', 'o''rta', 'yuqori')", name='ck_ai_modules_sensitivity'),
    sa.CheckConstraint('"group" IN (\'A\', \'B\', \'C\', \'D\', \'E\', \'F\')', name='ck_ai_modules_group'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_modules')
    # ### end Alembic commands ###
