"""add cameras table

Revision ID: f4c9709f9288
Revises: 0e7e3e7f3443
Create Date: 2026-08-01 12:31:27.777998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c9709f9288'
down_revision: Union[str, None] = '0e7e3e7f3443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('rtsp_path', sa.String(), nullable=True),
    sa.Column('rtsp_username', sa.String(), nullable=True),
    sa.Column('rtsp_password', sa.String(), nullable=True),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stream_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('faol', 'nofaol', 'tamirda')", name='ck_cameras_status'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_building_id'), 'cameras', ['building_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cameras_building_id'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
